spring.application.name=backend
# Config moi truong
#spring.profiles.active=prod
# Port
server.port=8081

server.servlet.context-path=/

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.datasource.url=${DB_URL:jdbc:mysql://139.162.31.27:3306/class_system_demo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:adminptit}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.datasource.driver-class-name=

# Optional: show SQL
spring.jpa.hibernate.ddl-auto=update

# Logging config for all environments (can be overridden in profile-specific files)
spring.main.banner-mode=console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Ho_Chi_Minh} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Ho_Chi_Minh} [%thread] %-5level %logger{36} - %msg%n

springdoc.packages-to-scan:com.vn.backend
spring.plugin.springsecurity.rest.token.storage.jwt.secret=KfB0zx1j7h5nxmTqksOguB7bMgy/4lFnyc6KmZrQh3MnGm02VsyiXQjZcJcmuXcD9Vibd4R6lqpYdqqFnlZ9yA==
spring.plugin.springsecurity.rest.token.storage.jwt.expiration = 360000
spring.plugin.springsecurity.rest.token.storage.jwt.refresh.expiration = 604800

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#default is 10
spring.datasource.hikari.maximum-pool-size=20
#default is same as max pool size
spring.datasource.hikari.minimum-idle=10
#default is 30 seconds
spring.datasource.hikari.connection-timeout=30000
#default is 600000 i.e 10 minutes
spring.datasource.hikari.idle-timeout=600000
#default is 1800000 i.e 30 minutes
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=hikari-connection-pool

cloudinary.cloud-name=dgvl8woja
cloudinary.api-key=934613154799643
cloudinary.api-secret=0rrg3DpEDFVB6KgP_hft_2QyLtc
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#file storage
file.path=${FILE_PATH:C:/uploads}
url.download.file=${URL_DOWNLOAD_FILE:http://localhost:8081/api/files/download/}
logging.level.root=info
logging.level.com.vn.backend=info
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate=ERROR
logging.level.org.springframework=warn
logging.file.name=logs/dev-app.log
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:139.162.31.27}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:DoAn2025PTIT}
spring.data.redis.database=0
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:dangbinh1770@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nkkm szbc ugwy mbgb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL
frontend.url=${FRONTEND_URL:http://139.162.31.27:3000}


