SORT_KEY=Sort key
SORT_ORDER=Sort order
PAGE_NUM=Page number
PAGE_SIZE=Page size
CLASS_NAME=Class name
CLASSROOM_STATUS=Classroom status
CLASSROOM_ID=Classroom id
CLASS_CODE_STATUS=Class code status
LATE_SUBMISSION_POLICY=Late Submission Policy
GRADE_CALCULATION_METHOD=Grade Calculation Method
CLASS_MEMBER_ROLE=Class member role
CLASS_MEMBER_STATUS=Class member status
MEMBER_ID=Member id
ASSIGNMENT_ID=Assignment id
SUBMISSION_ID=Submission id
ATTACHMENT_ID=Attachment id
USER_ID=User id
SUBJECT_CODE=Subject code
SUBJECT_NAME=Subject name
SUBJECT_ID=Subject id
EXAM_ID=Exam id
QUESTION_ID=Question id
ORDER_INDEX=Order index
SCORE=Score
TOPIC_ID=Topic id
DIFFICULTY_LEVEL=Difficulty level
TYPE=Type
CLASS_SCHEDULES=Class schedules
COURSE_OUTLINE_URL=Course Outline Url
START_TIME=Start time
END_TIME=End time
ROOM=Room
DAY_OF_WEEK=Day of week
REQUEST_TYPE=Request type
REQUEST_STATUS=Request status
CREATED_AT=Created at
CLASS_CODE=Class code